'use client';

import { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';
import { cn } from '@/lib/utils';
import type { ChatMarkdownContentProps } from './ChatMarkdownContent.types';

/**
 * Removes "Fontes:" or "Sources:" sections from AI responses.
 * These sections are often auto-generated by LlamaIndex and should be hidden.
 */
function removeSourcesSection(content: string): string {
  if (!content) return content;

  // Remove "Fontes:", "Sources:", "Fonte:", "Source:" sections and everything after
  const fontesPattern = /\n*(?:Fontes|Sources|Fonte|Source):\s*[\s\S]*$/i;
  return content.replace(fontesPattern, '').trim();
}

/**
 * Renders markdown content with proper styling and sanitization.
 *
 * Features:
 * - GitHub Flavored Markdown (tables, strikethrough, etc.)
 * - HTML sanitization for security
 * - Proper styling for code blocks, links, lists
 * - Optional removal of "Sources" section from AI responses
 *
 * @example
 * ```tsx
 * <ChatMarkdownContent
 *   content="**Hello** world! Check out [this link](https://example.com)"
 *   removeSourcesSection
 * />
 * ```
 */
export function ChatMarkdownContent({
  content,
  className,
  removeSourcesSection: shouldRemoveSources = true,
}: ChatMarkdownContentProps) {
  const processedContent = useMemo(() => {
    if (!content) return '';
    return shouldRemoveSources ? removeSourcesSection(content) : content;
  }, [content, shouldRemoveSources]);

  if (!processedContent) return null;

  return (
    <div
      className={cn(
        'prose prose-sm max-w-none',
        // Text styling
        'prose-p:my-2 prose-p:leading-relaxed',
        // Headings
        'prose-headings:font-semibold prose-headings:text-gray-900',
        'prose-h1:text-xl prose-h2:text-lg prose-h3:text-base',
        // Links
        'prose-a:text-primary-700 prose-a:no-underline hover:prose-a:underline',
        // Code blocks
        'prose-code:bg-gray-100 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:text-sm',
        'prose-code:before:content-none prose-code:after:content-none',
        'prose-pre:bg-gray-900 prose-pre:text-gray-100 prose-pre:rounded-md prose-pre:p-4',
        // Lists
        'prose-ul:my-2 prose-ol:my-2 prose-li:my-1',
        // Blockquotes
        'prose-blockquote:border-l-primary-500 prose-blockquote:bg-gray-50 prose-blockquote:py-1 prose-blockquote:px-4',
        // Tables
        'prose-table:border-collapse prose-th:bg-gray-100 prose-th:p-2 prose-td:p-2 prose-td:border prose-td:border-gray-200',
        // Strong/emphasis
        'prose-strong:font-semibold prose-strong:text-gray-900',
        className
      )}
    >
      <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeSanitize]}>
        {processedContent}
      </ReactMarkdown>
    </div>
  );
}
